"""Materialize a language-agnostic `TestSpec` into a runnable suite.

Only the pytest adapter is implemented in v1; new adapters can register
themselves via the `LanguageAdapter` registry. The generator never executes
the suite — that responsibility lives in ``protogenius.orchestrator`` so
that quota accounting (turns + walltime) can be centralized.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path
from typing import Protocol

from .spec_layer import TestCase, TestSpec


class LanguageAdapter(Protocol):
    """Materializer for one runner / language."""

    name: str

    def materialize(self, spec: TestSpec, target_dir: Path) -> list[Path]:  # pragma: no cover
        ...


_REGISTRY: dict[str, LanguageAdapter] = {}


def register(adapter: LanguageAdapter) -> None:
    _REGISTRY[adapter.name] = adapter


def materialize_spec(spec: TestSpec, target_dir: Path) -> list[Path]:
    """Group cases by runner_hint and dispatch to the matching adapter."""
    target_dir.mkdir(parents=True, exist_ok=True)
    by_runner: dict[str, list[TestCase]] = {}
    for case in spec.cases:
        by_runner.setdefault(case.runner_hint, []).append(case)

    paths: list[Path] = []
    for runner, cases in by_runner.items():
        adapter = _REGISTRY.get(runner)
        if adapter is None:
            paths.append(_fallback_markdown(runner, cases, target_dir))
            continue
        paths.extend(adapter.materialize(TestSpec(cases=cases), target_dir))
    return paths


def _fallback_markdown(runner: str, cases: list[TestCase], target_dir: Path) -> Path:
    """When no adapter matches, write a human-readable Markdown checklist."""
    target = target_dir / f"_unsupported_{runner}.md"
    lines = [
        f"# Unsupported runner: `{runner}`",
        "",
        "These cases could not be materialized automatically:",
        "",
    ]
    for case in cases:
        lines.append(f"## {case.id}")
        if case.description:
            lines.append(case.description)
        lines.append("**Steps**")
        lines.extend(f"- {step}" for step in case.steps)
        lines.append("**Expected**: " + case.expected)
        lines.append("")
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return target


# ---- built-in pytest adapter --------------------------------------------


class PytestAdapter:
    name: str = "pytest"

    def materialize(self, spec: TestSpec, target_dir: Path) -> list[Path]:
        lines = [
            '"""Generated by ProtoGenius. Do not edit by hand."""',
            "",
            "from __future__ import annotations",
            "",
            "import pytest",
            "",
        ]
        for case in spec.cases:
            lines.append(self._render_case(case))
        target = target_dir / "test_generated.py"
        target.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return [target]

    def _render_case(self, case: TestCase) -> str:
        body = ['    """']
        body.append(f"    Refs: {', '.join(case.refs) or '(none)'}")
        body.append(f"    Kind: {case.kind}")
        if case.pre:
            body.append("    Pre-conditions:")
            body.extend(f"      {line}" for line in case.pre.splitlines())
        body.append("    Steps:")
        body.extend(f"      - {step}" for step in case.steps)
        body.append("    Expected:")
        body.append(f"      {case.expected}")
        body.append('    """')
        body.append(
            f'    pytest.skip("Auto-generated stub for {case.id}; implement against the demo")'
        )
        return f"def test_{_safe(case.id)}() -> None:\n" + "\n".join(body)


_register: Callable[[LanguageAdapter], None] = register


def _safe(value: str) -> str:
    return "".join(ch if ch.isalnum() else "_" for ch in value).lower()


_register(PytestAdapter())
